namespace LeagueStalker.ServerResponse.LOLAPI
{
    public class Stats
    {
        public long participantId { get; set; }
        public bool win { get; set; }
        public long item0 { get; set; }
        public long item1 { get; set; }
        public long item2 { get; set; }
        public long item3 { get; set; }
        public long item4 { get; set; }
        public long item5 { get; set; }
        public long item6 { get; set; }
        public int kills { get; set; }
        public int deaths { get; set; }
        public int assists { get; set; }
        public long largestKillingSpree { get; set; }
        public long doubleKills { get; set; }
        public long tripleKills { get; set; }
        public long quadraKills { get; set; }
        public long pentaKills { get; set; }
        public long unrealKlls { get; set; }
        public long totalDamageDealt { get; set; }
        public long magicDamageDealt { get; set; }
        public long physicalDamageDealt { get; set; }
        public long trueDamageDealt { get; set; }
        public long largestCriticalStrike { get; set; }
        public long totalDamageDealtToChampions { get; set; }
        public long magicDamageDealtToChampions { get; set; }
        public long physicalDamageDealtToChampions { get; set; }
        public long trueDamageDealtToChampions { get; set; }
        public long totalHeal { get; set; }
        public long totalUnitsHealed { get; set; }
        public long damageSelfMitigated { get; set; }
        public long damageDealtToObjectives { get; set; }
        public long damageDealtToTurrets { get; set; }
        public long visionScore { get; set; }
        public long timeCCingOthers { get; set; }
        public long totalDamageTaken { get; set; }
        public long magicalDamageTaken { get; set; }
        public long physicalDamageTaken { get; set; }
        public long trueDamageTaken { get; set; }
        public long goldEarned { get; set; }
        public long goldSpent { get; set; }
        public long totalMinionsKilled { get; set; }
        public long neutralMinionsKilled { get; set; }
        public long totalTimeCrowdControlDealt { get; set; }
        public int champLevel { get; set; }
        public long visionWardsBoughtInGame { get; set; }
        public long sightWardsBoughtInGame { get; set; }
        public bool firstBloodKill { get; set; }
        public bool firstBloodAssist { get; set; }
        public long combatPlayerScore { get; set; }
        public long objectivePlayerScore { get; set; }
        public long totalPlayerScore { get; set; }
        public long totalScoreRank { get; set; }
        public long playerScore0 { get; set; }
        public long playerScore1 { get; set; }
        public long playerScore2 { get; set; }
        public long playerScore3 { get; set; }
        public long playerScore4 { get; set; }
        public long playerScore5 { get; set; }
        public long playerScore6 { get; set; }
        public long playerScore7 { get; set; }
        public long playerScore8 { get; set; }
        public long playerScore9 { get; set; }
        public long perk0 { get; set; }
        public long perk0Var1 { get; set; }
        public long perk0Var2 { get; set; }
        public long perk0Var3 { get; set; }
        public long perk1 { get; set; }
        public long perk1Var1 { get; set; }
        public long perk1Var2 { get; set; }
        public long perk1Var3 { get; set; }
        public long perk2 { get; set; }
        public long perk2Var1 { get; set; }
        public long perk2Var2 { get; set; }
        public long perk2Var3 { get; set; }
        public long perk3 { get; set; }
        public long perk3Var1 { get; set; }
        public long perk3Var2 { get; set; }
        public long perk3Var3 { get; set; }
        public long perk4 { get; set; }
        public long perk4Var1 { get; set; }
        public long perk4Var2 { get; set; }
        public long perk4Var3 { get; set; }
        public long perk5 { get; set; }
        public long perk5Var1 { get; set; }
        public long perk5Var2 { get; set; }
        public long perk5Var3 { get; set; }
        public long perkPrimaryStyle { get; set; }
        public long perkSubStyle { get; set; }

    }
}
